---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "<<DESCRIPTION>>"
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentDependencies:
  aws.greengrass.TokenExchangeService:
    VersionRequirement: ">=2.0.0"
    DependencyType: "HARD"
ComponentConfiguration:
  DefaultConfiguration:
    ComponentConfig:
      logging:
        level: "INFO"
        format: "%(asctime)s [%(levelname)s] %(filename)s %(funcName)s(%(lineno)d) [%(threadName)s]: %(message)s"
      heartbeat:
        intervalSecs: 5
        targets:
          - type: "messaging"
            config:
              destination: "ipc"
              topic: "heartbeat/{ThingName}/{ComponentName}"
        measures:
          cpu: true
          memory: true
          disk: false
      tags: {}
      metricEmission:
        target: "cloudwatch"
        namespace: "ggcommons"
        targetConfig:
          intervalSecs: 10
      component:
        global: {}
        instances: []
    accessControl:
      aws.greengrass.ipc.pubsub:
        "<<COMPONENTFULLNAME>>:ipc:1":
          policyDescription: Allows access to publish/subscribe to all topics on IPC
          operations:
            - "aws.greengrass#PublishToTopic"
            - "aws.greengrass#SubscribeToTopic"
          resources:
            - "*"
      aws.greengrass.ipc.mqttproxy:
        "<<COMPONENTFULLNAME>>:iotcore:1":
          policyDescription: Allows access to publish/subscribe to all topics on IoT Core.
          operations:
            - "aws.greengrass#PublishToIoTCore"
            - "aws.greengrass#SubscribeToIoTCore"
          resources:
            - "*"
      aws.greengrass.ShadowManager:
        "<<COMPONENTFULLNAME>>:shadow:1":
          policyDescription: Allows access to shadows.
          operations:
            - 'aws.greengrass#GetThingShadow'
            - 'aws.greengrass#UpdateThingShadow'
            - 'aws.greengrass#DeleteThingShadow'
          resources:
            - "*"
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/<<COMPONENT_NAME>>.zip"
        Unarchive: ZIP
    Lifecycle:
      Install:
        Script: |-
          pip3 install --user -r {artifacts:decompressedPath}/<<COMPONENT_NAME>>/requirements.txt
      Run:
        Script: |-
          python3 -u {artifacts:decompressedPath}/<<COMPONENT_NAME>>/main.py