"""Cross-language UNS conformance: replay ``uns-test-vectors/`` against this library.

Mirrors the vault-test-vectors loader pattern (test_credentials.py): the shared
vectors are generated by the Java canonical generator
(``UnsTestVectorsGeneratorTest``) and pin the normative UNS grammar
(UNS-CANONICAL-DESIGN §2.2/§4.1, D-U12/13/22/25/26):

- **build** — pair hierarchyLevels[i] with identityValues[level]; identityValues and
  component pass through the template sanitizer FIRST (the config identity-resolution
  path, pinning the D-U26 "sanitized => valid" equivalence); instance and channel are
  used verbatim. Topics compare byte-for-byte; failures by exact error code.
- **validate** — includeRoot-sensitive full-grammar validation (bound to a
  multi-level identity so the includeRoot input is the effective root mode, D-U25).
- **filter** — wildcard subscription filters, byte-for-byte.
- **guard** — the §4.1 reserved-class predicate (D-U24).
- **envelopes** — one golden full canonical JSON envelope per class: rebuild through
  the message builder (explicit uuid/timestamp/correlation_id setters + the vector
  identity + body) and compare STRUCTURALLY (member order is not normative, D-U22);
  reproduce the topic byte-for-byte from the vector identity.
- **bcast** (``bcast.json``, DESIGN-uns §9.3 layer 2 / §9.4) — the ``_bcast``
  republish (reconnect-rehydration) contract: the two broadcast command topics
  rebuilt byte-for-byte through the topic builder with the reserved ``_bcast``
  pseudo-component identity, the golden fire-and-forget notification envelopes (no
  identity/tags/reply_to, empty body), and the normative listener behavior constants
  (jitter window / coalescing cooldown) that
  :class:`~edgecommons.republish_listener.RepublishListener` must implement.

Some vector inputs deliberately carry raw C1 control bytes — parsed as JSON, never
preprocessed.
"""
import json
from pathlib import Path

import pytest

from edgecommons.config.manager.config_manager import ConfigManager
from edgecommons.messaging.identity import HierEntry, MessageIdentity
from edgecommons.messaging.message_builder import MessageBuilder
from edgecommons.messaging.messaging_client import MessagingClient
from edgecommons.uns import Uns, UnsClass, UnsScope, UnsValidationError

VECTORS_DIR = Path(__file__).resolve().parents[3] / "uns-test-vectors"

pytestmark = pytest.mark.skipif(
    not (VECTORS_DIR / "topics.json").exists(), reason="uns-test-vectors not present"
)


def _load(name):
    return json.loads((VECTORS_DIR / name).read_text(encoding="utf-8"))


def _cases(file_name, group):
    if not (VECTORS_DIR / file_name).exists():
        return []
    return _load(file_name)[group]


def _case_ids(cases):
    return [c["name"] for c in cases]


def _build_identity(inp):
    """The build-case identity contract: hierarchyLevels[i] pairs with
    identityValues[<level>]; identityValues and component pass through the sanitizer
    FIRST; instance is used verbatim. D-U28: the instance is optional — an absent
    ``instance`` key yields a component-scope identity (no instance token)."""
    hier = [
        HierEntry(level, ConfigManager.sanitize(inp["identityValues"][level]))
        for level in inp["hierarchyLevels"]
    ]
    return MessageIdentity(
        hier, ConfigManager.sanitize(inp["component"]), inp.get("instance")
    )


# An identity with a multi-level hierarchy (>= 2 levels) so the includeRoot input is
# the effective root mode for validate/filter (D-U25).
_MULTI_LEVEL_IDENTITY = MessageIdentity(
    [HierEntry("site", "dallas"), HierEntry("device", "gw-01")], "comp"
)


@pytest.mark.parametrize(
    "case", _cases("topics.json", "build"), ids=_case_ids(_cases("topics.json", "build"))
)
def test_vector_build(case):
    inp = case["input"]
    expected = case["expected"]
    identity = _build_identity(inp)
    uns = Uns(identity, inp["includeRoot"])
    cls = UnsClass.from_token(inp["class"])
    assert cls is not None, f"vector class '{inp['class']}' is not a UNS class"
    channel = inp.get("channel")

    if "topic" in expected:
        assert uns.topic(cls, channel) == expected["topic"]  # byte-for-byte
    else:
        with pytest.raises(UnsValidationError) as exc_info:
            uns.topic(cls, channel)
        assert exc_info.value.code == expected["error"]


@pytest.mark.parametrize(
    "case", _cases("topics.json", "validate"),
    ids=_case_ids(_cases("topics.json", "validate")),
)
def test_vector_validate(case):
    inp = case["input"]
    expected = case["expected"]
    uns = Uns(_MULTI_LEVEL_IDENTITY, inp["includeRoot"])

    if expected.get("ok"):
        uns.validate(inp["topic"])  # must not raise
    else:
        with pytest.raises(UnsValidationError) as exc_info:
            uns.validate(inp["topic"])
        assert exc_info.value.code == expected["error"]


@pytest.mark.parametrize(
    "case", _cases("topics.json", "filter"), ids=_case_ids(_cases("topics.json", "filter"))
)
def test_vector_filter(case):
    inp = case["input"]
    scope_in = inp["scope"]
    scope = UnsScope(
        site=scope_in.get("site"),
        device=scope_in.get("device"),
        component=scope_in.get("component"),
        instance=scope_in.get("instance"),
    )
    uns = Uns(_MULTI_LEVEL_IDENTITY, inp["includeRoot"])
    cls = UnsClass.from_token(inp["class"])
    assert uns.filter(cls, scope) == case["expected"]["filter"]  # byte-for-byte


@pytest.mark.parametrize(
    "case", _cases("topics.json", "guard"), ids=_case_ids(_cases("topics.json", "guard"))
)
def test_vector_guard(case):
    inp = case["input"]
    reserved = MessagingClient._reserved_class_of(inp["topic"], inp["includeRoot"])
    assert (reserved is not None) == case["expected"]["reserved"]


@pytest.mark.parametrize(
    "case", _cases("envelopes.json", "envelopes"),
    ids=_case_ids(_cases("envelopes.json", "envelopes")),
)
def test_vector_envelope(case):
    envelope = case["envelope"]
    header = envelope["header"]

    # (1) Parse the vector identity with the lenient wire parser.
    identity = MessageIdentity.from_dict(envelope["identity"])
    assert identity is not None, "golden envelope identity must parse"
    # The lenient parse round-trips structurally.
    assert identity.to_dict() == envelope["identity"]

    # (2) Rebuild the envelope through the builder with the pinned uuid/timestamp/
    # correlation_id and assert STRUCTURAL equality (D-U22: member order is not
    # normative; dict equality is structural).
    rebuilt = (
        MessageBuilder.create(header["name"], header["version"])
        .with_uuid(header["uuid"])
        .with_timestamp(header["timestamp"])
        .with_correlation_id(header["correlation_id"])
        .with_identity(identity)
        .with_payload(envelope["body"])
        .build()
    )
    assert rebuilt.to_dict() == envelope

    # (3) The other direction: the wire parser reproduces the same envelope.
    from edgecommons.messaging.message import Message

    parsed = Message.from_object(json.loads(json.dumps(envelope)))
    assert parsed.to_dict() == envelope

    # (4) Reproduce the topic byte-for-byte from the vector identity + class +
    # channel with includeRoot=false (all envelope vectors are rootless).
    cls = UnsClass.from_token(case["class"])
    topic = Uns(identity, False).topic(cls, case.get("channel"))
    assert topic == case["topic"]


# ===================== bcast.json — the _bcast republish contract =====================


def _bcast_commands():
    return _cases("bcast.json", "commands")


def _bcast_behavior():
    if not (VECTORS_DIR / "bcast.json").exists():
        return None
    return _load("bcast.json")["behavior"]


@pytest.mark.parametrize("case", _bcast_commands(), ids=_case_ids(_bcast_commands()))
def test_bcast_topic_and_envelope(case):
    """One bcast.json command vector: the topic reproduced byte-for-byte through the
    real topic builder with the reserved ``_bcast`` pseudo-component identity, and the
    fire-and-forget notification envelope (no identity/tags/reply_to, empty body)
    reproduced through the real ``MessageBuilder`` (D-U12)."""
    from edgecommons.republish_listener import RepublishListener

    inp = case["input"]
    assert inp["component"] == RepublishListener.BCAST_COMPONENT, (
        "'" + case["name"] + "' pseudo-component token"
    )
    identity = MessageIdentity(
        [HierEntry("device", inp["device"])], inp["component"], inp.get("instance")
    )
    cls = UnsClass.from_token(inp["class"])
    assert cls is not None, f"vector class '{inp['class']}' is not a UNS class"
    topic = Uns(identity, inp["includeRoot"]).topic(cls, inp["channel"])
    assert topic == case["topic"], "'" + case["name"] + "' topic"

    envelope = case["envelope"]
    header = envelope["header"]
    assert header["name"] == case["name"], "'" + case["name"] + "' header name"
    assert header["version"] == "1.0", "'" + case["name"] + "' header version"
    assert "reply_to" not in header, (
        "'" + case["name"] + "' is fire-and-forget - no reply_to"
    )
    assert "identity" not in envelope, (
        "'" + case["name"] + "' is built without a config-bound builder - no identity"
    )
    assert "tags" not in envelope, "'" + case["name"] + "' carries no tags"
    assert envelope["body"] == {}, "'" + case["name"] + "' body is the empty object"

    rebuilt = (
        MessageBuilder.create(header["name"], header["version"])
        .with_uuid(header["uuid"])
        .with_timestamp(header["timestamp"])
        .with_correlation_id(header["correlation_id"])
        .with_payload(envelope["body"])
        .build()
    )
    assert rebuilt.to_dict() == envelope, "'" + case["name"] + "' envelope"


def test_bcast_command_order():
    """bcast.json pins exactly the two republish commands, in order
    republish-state, republish-cfg."""
    from edgecommons.republish_listener import RepublishListener

    cases = _bcast_commands()
    if not cases:
        pytest.skip("bcast.json not present")
    assert [c["name"] for c in cases] == [
        RepublishListener.REPUBLISH_STATE,
        RepublishListener.REPUBLISH_CFG,
    ]


def test_bcast_behavior_constants():
    """The normative listener behavior constants (all four languages) must equal this
    implementation's."""
    from edgecommons.republish_listener import RepublishListener

    behavior = _bcast_behavior()
    if behavior is None:
        pytest.skip("bcast.json not present")
    assert behavior["jitterWindowMs"] == RepublishListener.JITTER_WINDOW_MS, (
        "jitterWindowMs must equal the implementation's window"
    )
    assert behavior["cooldownMs"] == RepublishListener.COOLDOWN_MS, (
        "cooldownMs must equal the implementation's cooldown"
    )
    assert behavior["replyTo"] is False, (
        "the republish broadcast never carries a reply_to"
    )
