"""Cross-language UNS conformance: replay ``uns-test-vectors/`` against this library.

Mirrors the vault-test-vectors loader pattern (test_credentials.py): the shared
vectors are generated by the Java canonical generator
(``UnsTestVectorsGeneratorTest``) and pin the normative UNS grammar
(UNS-CANONICAL-DESIGN §2.2/§4.1, D-U12/13/22/25/26):

- **build** — pair hierarchyLevels[i] with identityValues[level]; identityValues and
  component pass through the template sanitizer FIRST (the config identity-resolution
  path, pinning the D-U26 "sanitized => valid" equivalence); instance and channel are
  used verbatim. Topics compare byte-for-byte; failures by exact error code.
- **validate** — includeRoot-sensitive full-grammar validation (bound to a
  multi-level identity so the includeRoot input is the effective root mode, D-U25).
- **filter** — wildcard subscription filters, byte-for-byte.
- **guard** — the §4.1 reserved-class predicate (D-U24).
- **envelopes** — one golden full canonical JSON envelope per class: rebuild through
  the message builder (explicit uuid/timestamp/correlation_id setters + the vector
  identity + body) and compare STRUCTURALLY (member order is not normative, D-U22);
  reproduce the topic byte-for-byte from the vector identity.

Some vector inputs deliberately carry raw C1 control bytes — parsed as JSON, never
preprocessed.
"""
import json
from pathlib import Path

import pytest

from ggcommons.config.manager.config_manager import ConfigManager
from ggcommons.messaging.identity import HierEntry, MessageIdentity
from ggcommons.messaging.message_builder import MessageBuilder
from ggcommons.messaging.messaging_client import MessagingClient
from ggcommons.uns import Uns, UnsClass, UnsScope, UnsValidationError

VECTORS_DIR = Path(__file__).resolve().parents[3] / "uns-test-vectors"

pytestmark = pytest.mark.skipif(
    not (VECTORS_DIR / "topics.json").exists(), reason="uns-test-vectors not present"
)


def _load(name):
    return json.loads((VECTORS_DIR / name).read_text(encoding="utf-8"))


def _cases(file_name, group):
    if not (VECTORS_DIR / file_name).exists():
        return []
    return _load(file_name)[group]


def _case_ids(cases):
    return [c["name"] for c in cases]


def _build_identity(inp):
    """The build-case identity contract: hierarchyLevels[i] pairs with
    identityValues[<level>]; identityValues and component pass through the sanitizer
    FIRST; instance is used verbatim."""
    hier = [
        HierEntry(level, ConfigManager.sanitize(inp["identityValues"][level]))
        for level in inp["hierarchyLevels"]
    ]
    return MessageIdentity(
        hier, ConfigManager.sanitize(inp["component"]), inp["instance"]
    )


# An identity with a multi-level hierarchy (>= 2 levels) so the includeRoot input is
# the effective root mode for validate/filter (D-U25).
_MULTI_LEVEL_IDENTITY = MessageIdentity(
    [HierEntry("site", "dallas"), HierEntry("device", "gw-01")], "comp"
)


@pytest.mark.parametrize(
    "case", _cases("topics.json", "build"), ids=_case_ids(_cases("topics.json", "build"))
)
def test_vector_build(case):
    inp = case["input"]
    expected = case["expected"]
    identity = _build_identity(inp)
    uns = Uns(identity, inp["includeRoot"])
    cls = UnsClass.from_token(inp["class"])
    assert cls is not None, f"vector class '{inp['class']}' is not a UNS class"
    channel = inp.get("channel")

    if "topic" in expected:
        assert uns.topic(cls, channel) == expected["topic"]  # byte-for-byte
    else:
        with pytest.raises(UnsValidationError) as exc_info:
            uns.topic(cls, channel)
        assert exc_info.value.code == expected["error"]


@pytest.mark.parametrize(
    "case", _cases("topics.json", "validate"),
    ids=_case_ids(_cases("topics.json", "validate")),
)
def test_vector_validate(case):
    inp = case["input"]
    expected = case["expected"]
    uns = Uns(_MULTI_LEVEL_IDENTITY, inp["includeRoot"])

    if expected.get("ok"):
        uns.validate(inp["topic"])  # must not raise
    else:
        with pytest.raises(UnsValidationError) as exc_info:
            uns.validate(inp["topic"])
        assert exc_info.value.code == expected["error"]


@pytest.mark.parametrize(
    "case", _cases("topics.json", "filter"), ids=_case_ids(_cases("topics.json", "filter"))
)
def test_vector_filter(case):
    inp = case["input"]
    scope_in = inp["scope"]
    scope = UnsScope(
        site=scope_in.get("site"),
        device=scope_in.get("device"),
        component=scope_in.get("component"),
        instance=scope_in.get("instance"),
    )
    uns = Uns(_MULTI_LEVEL_IDENTITY, inp["includeRoot"])
    cls = UnsClass.from_token(inp["class"])
    assert uns.filter(cls, scope) == case["expected"]["filter"]  # byte-for-byte


@pytest.mark.parametrize(
    "case", _cases("topics.json", "guard"), ids=_case_ids(_cases("topics.json", "guard"))
)
def test_vector_guard(case):
    inp = case["input"]
    reserved = MessagingClient._reserved_class_of(inp["topic"], inp["includeRoot"])
    assert (reserved is not None) == case["expected"]["reserved"]


@pytest.mark.parametrize(
    "case", _cases("envelopes.json", "envelopes"),
    ids=_case_ids(_cases("envelopes.json", "envelopes")),
)
def test_vector_envelope(case):
    envelope = case["envelope"]
    header = envelope["header"]

    # (1) Parse the vector identity with the lenient wire parser.
    identity = MessageIdentity.from_dict(envelope["identity"])
    assert identity is not None, "golden envelope identity must parse"
    # The lenient parse round-trips structurally.
    assert identity.to_dict() == envelope["identity"]

    # (2) Rebuild the envelope through the builder with the pinned uuid/timestamp/
    # correlation_id and assert STRUCTURAL equality (D-U22: member order is not
    # normative; dict equality is structural).
    rebuilt = (
        MessageBuilder.create(header["name"], header["version"])
        .with_uuid(header["uuid"])
        .with_timestamp(header["timestamp"])
        .with_correlation_id(header["correlation_id"])
        .with_identity(identity)
        .with_payload(envelope["body"])
        .build()
    )
    assert rebuilt.to_dict() == envelope

    # (3) The other direction: the wire parser reproduces the same envelope.
    from ggcommons.messaging.message import Message

    parsed = Message.from_object(json.loads(json.dumps(envelope)))
    assert parsed.to_dict() == envelope

    # (4) Reproduce the topic byte-for-byte from the vector identity + class +
    # channel with includeRoot=false (all envelope vectors are rootless).
    cls = UnsClass.from_token(case["class"])
    topic = Uns(identity, False).topic(cls, case.get("channel"))
    assert topic == case["topic"]
