/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
package com.breissinger.ggcommons.messaging;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Unit tests for {@link MessageHeader} construction, getters, request preparation,
 * and JSON (snake_case) round-trips. Complements MessageHeaderBuilderTest by
 * exercising the constructor and fromDict()/toDict() paths directly.
 */
class MessageHeaderValueTest {

    @Test
    void sixArgConstructorPreservesExplicitValues() {
        MessageHeader h = new MessageHeader("Name", "1.0", "corr", "2024-01-01T00:00:00Z",
                "uuid-1", "reply/here");

        assertEquals("Name", h.getName());
        assertEquals("1.0", h.getVersion());
        assertEquals("corr", h.getCorrelationId());
        assertEquals("2024-01-01T00:00:00Z", h.getTimestamp());
        assertEquals("reply/here", h.getReplyTo());
    }

    @Test
    void constructorDefaultsCorrelationTimestampAndUuid() {
        MessageHeader h = new MessageHeader("Name", "1.0", null, null, null, null);

        assertNotNull(h.getCorrelationId());
        assertNotNull(h.getTimestamp());
        assertNull(h.getReplyTo());
    }

    @Test
    void getCorrelationIdLazilyGeneratesWhenNull() {
        // fromDict with name+version absent goes through the constructor with the supplied
        // (null) correlationId, but the constructor itself generates one. Use a header that
        // explicitly has a null correlation id by reflecting through setCorrelationId(null).
        MessageHeader h = new MessageHeader("Name", "1.0", "corr", "ts", "uuid", null);
        h.setCorrelationId(null);
        String generated = h.getCorrelationId();
        assertNotNull(generated);
        // subsequent calls return the same generated value
        assertEquals(generated, h.getCorrelationId());
    }

    @Test
    void makeRequestWithExplicitReplyTo() {
        MessageHeader h = new MessageHeader("Name", "1.0", "corr", "ts", "uuid", null);
        String replyTo = h.makeRequest("explicit/reply");
        assertEquals("explicit/reply", replyTo);
        assertEquals("explicit/reply", h.getReplyTo());
    }

    @Test
    void makeRequestAutoGeneratesReplyTopicWithPrefix() {
        MessageHeader h = new MessageHeader("Name", "1.0", "corr", "ts", "uuid", null);
        String replyTo = h.makeRequest(null);
        assertNotNull(replyTo);
        assertTrue(replyTo.startsWith(MessageHeader.REPLY_MESSAGE_TOPIC_PREFIX));
        assertEquals(replyTo, h.getReplyTo());
    }

    @Test
    void setCorrelationIdOverwrites() {
        MessageHeader h = new MessageHeader("Name", "1.0", "corr", "ts", "uuid", null);
        h.setCorrelationId("new-corr");
        assertEquals("new-corr", h.getCorrelationId());
    }

    @Test
    void fromDictFullHeaderRoundTrips() {
        JsonObject src = new JsonObject();
        src.addProperty("name", "Evt");
        src.addProperty("version", "3.0");
        src.addProperty("timestamp", "2024-05-05T12:00:00Z");
        src.addProperty("uuid", "uuid-xyz");
        src.addProperty("correlation_id", "corr-xyz");
        src.addProperty("reply_to", "reply/xyz");

        MessageHeader h = MessageHeader.fromDict(src);

        assertEquals("Evt", h.getName());
        assertEquals("3.0", h.getVersion());
        assertEquals("2024-05-05T12:00:00Z", h.getTimestamp());
        assertEquals("corr-xyz", h.getCorrelationId());
        assertEquals("reply/xyz", h.getReplyTo());

        JsonObject dict = h.toDict();
        assertEquals("Evt", dict.get("name").getAsString());
        assertEquals("corr-xyz", dict.get("correlation_id").getAsString());
        assertEquals("reply/xyz", dict.get("reply_to").getAsString());
        assertEquals("uuid-xyz", dict.get("uuid").getAsString());
    }

    @Test
    void fromDictPartialHeaderMissingNameUsesNullableConstructor() {
        // Missing name => uses the constructor path (not the builder), version preserved.
        JsonObject src = new JsonObject();
        src.addProperty("version", "1.0");
        src.addProperty("correlation_id", "corr-partial");

        MessageHeader h = MessageHeader.fromDict(src);

        assertNull(h.getName());
        assertEquals("1.0", h.getVersion());
        assertEquals("corr-partial", h.getCorrelationId());
        // timestamp/uuid auto-generated by constructor
        assertNotNull(h.getTimestamp());
    }

    @Test
    void toDictOmitsReplyToWhenNull() {
        MessageHeader h = new MessageHeader("Name", "1.0", "corr", "ts", "uuid", null);
        JsonObject dict = h.toDict();
        assertFalse(dict.has("reply_to"));
        assertTrue(dict.has("correlation_id"));
    }

    @Test
    void toStringIsValidJson() {
        MessageHeader h = new MessageHeader("Name", "1.0", "corr", "ts", "uuid", "reply/x");
        JsonObject reparsed = JsonParser.parseString(h.toString()).getAsJsonObject();
        assertEquals("Name", reparsed.get("name").getAsString());
        assertEquals("reply/x", reparsed.get("reply_to").getAsString());
    }
}
