/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A producer handle to one telemetry stream. */
export declare class StreamHandle {
  /** Append one record; resolves once durable per the stream's fsync policy. */
  append(partitionKey: string, timestampMs: number, payload: Buffer): void
  /** Force this stream's buffer durably to disk (does not wait for export). */
  flush(): void
}

/** Owns the native streaming service. */
export declare class StreamService {
  /** Open every stream in `configJson` (the `streaming` section; templates pre-resolved). */
  static open(configJson: string): StreamService
  /** A handle to the named stream (throws ERR_UNKNOWN_STREAM if not configured). */
  stream(name: string): StreamHandle
  /** A stats snapshot for the named stream (throws ERR_UNKNOWN_STREAM if not configured). */
  stats(name: string): StreamStats
  /** Flush every buffer, stop the export engines, and free the service. Idempotent. */
  close(): void
}

/** One forwarded log event (level: 1=ERROR..5=TRACE). */
export interface LogEvent {
  level: number
  target: string
  message: string
}

/**
 * Register a callback that receives core log events `{ level, target, message }`. Idempotent;
 * installs the forwarding subscriber on first call.
 */
export declare function setLogCallback(callback: ((err: Error | null, arg: LogEvent) => void)): void

/** A snapshot of one stream's buffer + export progress (mirrors `ggsl_stats_t`). */
export interface StreamStats {
  appendedTotal: number
  exportedTotal: number
  droppedTotal: number
  retriesTotal: number
  failedTotal: number
  backlog: number
  diskBytes: number
  ackedOffset: number
  nextOffset: number
  oldestUnackedAgeMs: number
}
