RecipeFormatVersion: '2020-01-25'
ComponentName: <<COMPONENTFULLNAME>>
ComponentVersion: 1.0.0
ComponentDescription: <<DESCRIPTION>>
ComponentPublisher: <<AUTHOR>>
ComponentConfiguration:
  DefaultConfiguration:
    ComponentConfig:
      logging:
        level: INFO
        rust_format: '{timestamp} [{level}] [{component}] {target} - {message}'
      heartbeat:
        enabled: true
        intervalSecs: 5
        destination: local
        measures:
          cpu: true
          memory: true
          disk: false
      metricEmission:
        target: log
        namespace: edgecommons
        targetConfig:
          logFileName: /greengrass/v2/work/{ComponentFullName}/metric.log
      tags:
        appId: Test
        site: Chantilly
      component:
        global:
          defaults:
            tickMs: 10000
        instances:
        - id: rollup
          subscribe:
          - ecv1/+/+/+/data/#
          publishTopic: ecv1/gw-01/<<BINNAME>>/rollup/data/summary
          target: local
          pipeline:
          - fieldEquals:
              path: signal.id
              value: temperature-1
          - countPerTick: {}
          tickMs: 10000
    accessControl:
      aws.greengrass.ipc.pubsub:
        <<COMPONENTFULLNAME>>:pubsub:1:
          policyDescription: Allows access to publish/subscribe to all local topics.
          operations:
          - aws.greengrass#PublishToTopic
          - aws.greengrass#SubscribeToTopic
          resources:
          - '*'
      aws.greengrass.ipc.mqttproxy:
        <<COMPONENTFULLNAME>>:northbound:1:
          policyDescription: Allows access to publish/subscribe to all topics on IoT Core.
          operations:
          - aws.greengrass#PublishToIoTCore
          - aws.greengrass#SubscribeToIoTCore
          resources:
          - '*'
      aws.greengrass.ShadowManager:
        <<COMPONENTFULLNAME>>:shadow:1:
          policyDescription: Allows access to thing shadows.
          operations:
          - aws.greengrass#GetThingShadow
          - aws.greengrass#UpdateThingShadow
          - aws.greengrass#DeleteThingShadow
          resources:
          - '*'
Manifests:
- Platform:
    os: linux
  Artifacts:
  - URI: s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/<<BINNAME>>
  Lifecycle:
    Install:
      Script: chmod +x {artifacts:path}/<<BINNAME>>
    Run:
      Script: '{artifacts:path}/<<BINNAME>> --platform GREENGRASS -c GG_CONFIG'
